import { PrismaClient } from '@prisma/client';
import { hashPassword } from '@/utils/auth';
import { logger } from '@/utils/logger';
import { generateSlug } from '@/utils/helpers';

const prisma = new PrismaClient();

async function main() {
  logger.info('🌱 Starting database seed...');

  // Create admin user
  const adminPassword = await hashPassword('admin123');
  const admin = await prisma.user.upsert({
    where: { email: 'admin@flowerhub.com' },
    update: {},
    create: {
      email: 'admin@flowerhub.com',
      password: adminPassword,
      firstName: 'Admin',
      lastName: 'User',
      role: 'SUPER_ADMIN',
      isEmailVerified: true,
    },
  });

  logger.info('✅ Admin user created:', admin.email);

  // Create test user
  const userPassword = await hashPassword('user123');
  const user = await prisma.user.upsert({
    where: { email: 'user@flowerhub.com' },
    update: {},
    create: {
      email: 'user@flowerhub.com',
      password: userPassword,
      firstName: 'John',
      lastName: 'Doe',
      role: 'USER',
      isEmailVerified: true,
    },
  });

  logger.info('✅ Test user created:', user.email);

  // Create comprehensive product categories
  const categories = [
    {
      name: 'Roses',
      slug: generateSlug('Roses'),
      description: 'Beautiful roses in various colors and arrangements',
      image: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=500',
      sortOrder: 1,
    },
    {
      name: 'Tulips',
      slug: generateSlug('Tulips'),
      description: 'Elegant tulips perfect for any occasion',
      image: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=500',
      sortOrder: 2,
    },
    {
      name: 'Lilies',
      slug: generateSlug('Lilies'),
      description: 'Fragrant lilies that bring elegance to any space',
      image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
      sortOrder: 3,
    },
    {
      name: 'Sunflowers',
      slug: generateSlug('Sunflowers'),
      description: 'Bright and cheerful sunflowers to brighten your day',
      image: 'https://images.unsplash.com/photo-1597848212624-e17eb5d2e0b4?w=500',
      sortOrder: 4,
    },
    {
      name: 'Orchids',
      slug: generateSlug('Orchids'),
      description: 'Exotic orchids for the sophisticated flower lover',
      image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500',
      sortOrder: 5,
    },
    {
      name: 'Bouquets',
      slug: generateSlug('Bouquets'),
      description: 'Beautiful flower bouquets for any occasion',
      image: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=500',
      sortOrder: 6,
    },
    {
      name: 'Arrangements',
      slug: generateSlug('Arrangements'),
      description: 'Elegant flower arrangements for home and office',
      image: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=500',
      sortOrder: 7,
    },
    {
      name: 'Plants',
      slug: generateSlug('Plants'),
      description: 'Live plants and potted flowers',
      image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
      sortOrder: 8,
    },
    {
      name: 'Centerpieces',
      slug: generateSlug('Centerpieces'),
      description: 'Beautiful centerpieces for special occasions',
      image: 'https://images.unsplash.com/photo-1597848212624-e17eb5d2e0b4?w=500',
      sortOrder: 9,
    },
    {
      name: 'Decorations',
      slug: generateSlug('Decorations'),
      description: 'Decorative flowers and arrangements',
      image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500',
      sortOrder: 10,
    },
  ];

  const createdCategories = [];
  for (const categoryData of categories) {
    const category = await prisma.productCategory.upsert({
      where: { slug: categoryData.slug },
      update: {},
      create: categoryData,
    });
    createdCategories.push(category);
    logger.info('✅ Category created:', category.name);
  }

  // Create comprehensive sample products
  const products = [
    // Roses
    {
      name: 'Red Rose Bouquet',
      slug: generateSlug('Red Rose Bouquet'),
      description: 'A stunning bouquet of 12 red roses, perfect for expressing love and romance. Each rose is carefully selected for its beauty and freshness.',
      price: 45.99,
      originalPrice: 55.99,
      categoryId: createdCategories[0]?.id || '',
      subcategory: 'Bouquets',
      images: [
        'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800',
        'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
      ],
      colors: ['Red'],
      sizes: ['Small', 'Medium', 'Large'],
      stockCount: 50,
      rating: 4.8,
      reviewCount: 24,
      tags: ['romance', 'valentine', 'anniversary'],
      features: ['Fresh cut', 'Long lasting', 'Beautiful presentation'],
      care: ['Keep in cool place', 'Change water daily', 'Trim stems'],
      isActive: true,
      isFeatured: true,
      weight: 0.5,
      length: 30,
      width: 20,
      height: 40,
      dimensionUnit: 'cm',
    },
    {
      name: 'Pink Rose Arrangement',
      slug: generateSlug('Pink Rose Arrangement'),
      description: 'Delicate pink roses arranged in an elegant vase. Perfect for birthdays, congratulations, or just to brighten someone\'s day.',
      price: 38.99,
      categoryId: createdCategories[0]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
        'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800',
      ],
      colors: ['Pink'],
      sizes: ['Medium', 'Large'],
      stockCount: 35,
      rating: 4.6,
      reviewCount: 16,
      tags: ['pink', 'delicate', 'birthday'],
      features: ['Soft pink color', 'Elegant vase', 'Fresh cut'],
      care: ['Keep in cool place', 'Change water daily'],
      isActive: true,
      isFeatured: false,
      weight: 0.4,
      length: 25,
      width: 15,
      height: 35,
      dimensionUnit: 'cm',
    },
    // Tulips
    {
      name: 'Mixed Tulip Arrangement',
      slug: generateSlug('Mixed Tulip Arrangement'),
      description: 'A colorful arrangement of mixed tulips in various colors. Perfect for spring celebrations and home decoration.',
      price: 32.99,
      categoryId: createdCategories[1]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
        'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
      ],
      colors: ['Red', 'Yellow', 'Pink', 'Purple'],
      sizes: ['Medium', 'Large'],
      stockCount: 30,
      rating: 4.6,
      reviewCount: 18,
      tags: ['spring', 'colorful', 'home decor'],
      features: ['Mixed colors', 'Seasonal', 'Fresh cut'],
      care: ['Keep in cool place', 'Change water every 2 days'],
      isActive: true,
      isFeatured: false,
      weight: 0.3,
      length: 25,
      width: 15,
      height: 35,
      dimensionUnit: 'cm',
    },
    {
      name: 'Yellow Tulip Bouquet',
      slug: generateSlug('Yellow Tulip Bouquet'),
      description: 'Bright yellow tulips that bring sunshine to any room. Perfect for spring celebrations and cheerful occasions.',
      price: 28.99,
      categoryId: createdCategories[1]?.id || '',
      subcategory: 'Bouquets',
      images: [
        'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
        'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
      ],
      colors: ['Yellow'],
      sizes: ['Small', 'Medium'],
      stockCount: 25,
      rating: 4.5,
      reviewCount: 12,
      tags: ['yellow', 'spring', 'cheerful'],
      features: ['Bright yellow', 'Fresh cut', 'Spring seasonal'],
      care: ['Keep in cool place', 'Change water every 2 days'],
      isActive: true,
      isFeatured: false,
      weight: 0.2,
      length: 20,
      width: 10,
      height: 30,
      dimensionUnit: 'cm',
    },
    // Lilies
    {
      name: 'White Lily Centerpiece',
      slug: generateSlug('White Lily Centerpiece'),
      description: 'Elegant white lilies arranged in a beautiful centerpiece. Perfect for weddings, anniversaries, and special occasions.',
      price: 65.99,
      originalPrice: 75.99,
      categoryId: createdCategories[2]?.id || '',
      subcategory: 'Centerpieces',
      images: [
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['White'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 20,
      rating: 4.9,
      reviewCount: 12,
      tags: ['elegant', 'wedding', 'anniversary', 'white'],
      features: ['Premium quality', 'Elegant design', 'Long lasting'],
      care: ['Keep away from direct sunlight', 'Change water daily'],
      isActive: true,
      isFeatured: true,
      weight: 1.2,
      length: 40,
      width: 30,
      height: 50,
      dimensionUnit: 'cm',
    },
    {
      name: 'Pink Lily Arrangement',
      slug: generateSlug('Pink Lily Arrangement'),
      description: 'Soft pink lilies in a modern arrangement. Perfect for adding elegance to any space.',
      price: 52.99,
      categoryId: createdCategories[2]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
      ],
      colors: ['Pink'],
      sizes: ['Medium', 'Large'],
      stockCount: 18,
      rating: 4.7,
      reviewCount: 9,
      tags: ['pink', 'elegant', 'modern'],
      features: ['Soft pink color', 'Modern design', 'Fragrant'],
      care: ['Keep away from direct sunlight', 'Change water daily'],
      isActive: true,
      isFeatured: false,
      weight: 0.8,
      length: 30,
      width: 20,
      height: 40,
      dimensionUnit: 'cm',
    },
    // Sunflowers
    {
      name: 'Sunflower Bouquet',
      slug: generateSlug('Sunflower Bouquet'),
      description: 'Bright and cheerful sunflowers arranged in a beautiful bouquet. Perfect for bringing joy and warmth to any space.',
      price: 28.99,
      categoryId: createdCategories[3]?.id || '',
      subcategory: 'Bouquets',
      images: [
        'https://images.unsplash.com/photo-1597848212624-e17eb5d2e0b4?w=800',
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      ],
      colors: ['Yellow'],
      sizes: ['Medium', 'Large'],
      stockCount: 40,
      rating: 4.7,
      reviewCount: 15,
      tags: ['cheerful', 'bright', 'summer'],
      features: ['Bright yellow', 'Large blooms', 'Fresh cut'],
      care: ['Keep in bright area', 'Change water every 2 days'],
      isActive: true,
      isFeatured: false,
      weight: 0.8,
      length: 35,
      width: 25,
      height: 45,
      dimensionUnit: 'cm',
    },
    {
      name: 'Sunflower Centerpiece',
      slug: generateSlug('Sunflower Centerpiece'),
      description: 'A stunning centerpiece featuring sunflowers and seasonal greens. Perfect for autumn celebrations.',
      price: 42.99,
      categoryId: createdCategories[3]?.id || '',
      subcategory: 'Centerpieces',
      images: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        'https://images.unsplash.com/photo-1597848212624-e17eb5d2e0b4?w=800',
      ],
      colors: ['Yellow', 'Green'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 22,
      rating: 4.8,
      reviewCount: 11,
      tags: ['autumn', 'centerpiece', 'seasonal'],
      features: ['Seasonal greens', 'Large sunflowers', 'Autumn colors'],
      care: ['Keep in bright area', 'Change water every 2 days'],
      isActive: true,
      isFeatured: true,
      weight: 1.0,
      length: 35,
      width: 30,
      height: 50,
      dimensionUnit: 'cm',
    },
    // Orchids
    {
      name: 'Purple Orchid Plant',
      slug: generateSlug('Purple Orchid Plant'),
      description: 'Exotic purple orchid plant in a decorative pot. Perfect for adding elegance and sophistication to any room.',
      price: 89.99,
      originalPrice: 99.99,
      categoryId: createdCategories[4]?.id || '',
      subcategory: 'Plants',
      images: [
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
      ],
      colors: ['Purple'],
      sizes: ['Medium', 'Large'],
      stockCount: 15,
      rating: 4.5,
      reviewCount: 8,
      tags: ['exotic', 'elegant', 'plant', 'purple'],
      features: ['Live plant', 'Decorative pot', 'Long blooming'],
      care: ['Water weekly', 'Bright indirect light', 'High humidity'],
      isActive: true,
      isFeatured: true,
      weight: 2.0,
      length: 20,
      width: 20,
      height: 60,
      dimensionUnit: 'cm',
    },
    {
      name: 'White Orchid Arrangement',
      slug: generateSlug('White Orchid Arrangement'),
      description: 'Pure white orchids in an elegant arrangement. Perfect for sophisticated spaces and special occasions.',
      price: 95.99,
      categoryId: createdCategories[4]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['White'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 12,
      rating: 4.6,
      reviewCount: 6,
      tags: ['white', 'sophisticated', 'elegant'],
      features: ['Pure white', 'Elegant design', 'Long lasting'],
      care: ['Water weekly', 'Bright indirect light', 'High humidity'],
      isActive: true,
      isFeatured: false,
      weight: 1.5,
      length: 25,
      width: 25,
      height: 55,
      dimensionUnit: 'cm',
    },
    // Bouquets
    {
      name: 'Mixed Spring Bouquet',
      slug: generateSlug('Mixed Spring Bouquet'),
      description: 'A beautiful mix of spring flowers including roses, tulips, and seasonal blooms. Perfect for any spring celebration.',
      price: 35.99,
      categoryId: createdCategories[5]?.id || '',
      subcategory: 'Bouquets',
      images: [
        'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800',
        'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
      ],
      colors: ['Mixed'],
      sizes: ['Medium', 'Large'],
      stockCount: 45,
      rating: 4.7,
      reviewCount: 20,
      tags: ['spring', 'mixed', 'colorful'],
      features: ['Mixed flowers', 'Spring seasonal', 'Colorful'],
      care: ['Keep in cool place', 'Change water daily'],
      isActive: true,
      isFeatured: true,
      weight: 0.6,
      length: 30,
      width: 20,
      height: 40,
      dimensionUnit: 'cm',
    },
    {
      name: 'Romantic Red Bouquet',
      slug: generateSlug('Romantic Red Bouquet'),
      description: 'A romantic bouquet of red roses and complementary flowers. Perfect for expressing love and passion.',
      price: 48.99,
      originalPrice: 58.99,
      categoryId: createdCategories[5]?.id || '',
      subcategory: 'Bouquets',
      images: [
        'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
        'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800',
      ],
      colors: ['Red'],
      sizes: ['Medium', 'Large'],
      stockCount: 30,
      rating: 4.9,
      reviewCount: 25,
      tags: ['romantic', 'red', 'love'],
      features: ['Romantic design', 'Red roses', 'Premium quality'],
      care: ['Keep in cool place', 'Change water daily'],
      isActive: true,
      isFeatured: true,
      weight: 0.7,
      length: 35,
      width: 25,
      height: 45,
      dimensionUnit: 'cm',
    },
    // Arrangements
    {
      name: 'Modern White Arrangement',
      slug: generateSlug('Modern White Arrangement'),
      description: 'A modern white flower arrangement perfect for contemporary spaces. Clean, elegant, and sophisticated.',
      price: 55.99,
      categoryId: createdCategories[6]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['White'],
      sizes: ['Medium', 'Large'],
      stockCount: 25,
      rating: 4.6,
      reviewCount: 14,
      tags: ['modern', 'white', 'contemporary'],
      features: ['Modern design', 'White flowers', 'Contemporary style'],
      care: ['Keep in cool place', 'Change water daily'],
      isActive: true,
      isFeatured: false,
      weight: 0.8,
      length: 30,
      width: 20,
      height: 40,
      dimensionUnit: 'cm',
    },
    {
      name: 'Tropical Arrangement',
      slug: generateSlug('Tropical Arrangement'),
      description: 'A vibrant tropical arrangement with exotic flowers and lush greenery. Perfect for bringing the tropics home.',
      price: 62.99,
      categoryId: createdCategories[6]?.id || '',
      subcategory: 'Arrangements',
      images: [
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['Mixed', 'Green'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 18,
      rating: 4.5,
      reviewCount: 10,
      tags: ['tropical', 'exotic', 'vibrant'],
      features: ['Tropical flowers', 'Lush greenery', 'Vibrant colors'],
      care: ['Keep in bright area', 'Change water every 2 days'],
      isActive: true,
      isFeatured: false,
      weight: 1.1,
      length: 35,
      width: 25,
      height: 45,
      dimensionUnit: 'cm',
    },
    // Plants
    {
      name: 'Succulent Garden',
      slug: generateSlug('Succulent Garden'),
      description: 'A beautiful collection of succulents in a decorative planter. Low maintenance and perfect for any space.',
      price: 34.99,
      categoryId: createdCategories[7]?.id || '',
      subcategory: 'Plants',
      images: [
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['Green', 'Mixed'],
      sizes: ['Small', 'Medium'],
      stockCount: 40,
      rating: 4.4,
      reviewCount: 16,
      tags: ['succulent', 'low maintenance', 'decorative'],
      features: ['Low maintenance', 'Decorative planter', 'Mixed succulents'],
      care: ['Water weekly', 'Bright indirect light', 'Well-draining soil'],
      isActive: true,
      isFeatured: false,
      weight: 1.5,
      length: 15,
      width: 15,
      height: 20,
      dimensionUnit: 'cm',
    },
    {
      name: 'Fiddle Leaf Fig',
      slug: generateSlug('Fiddle Leaf Fig'),
      description: 'A stunning fiddle leaf fig plant that adds elegance to any room. Perfect for modern interior design.',
      price: 79.99,
      originalPrice: 89.99,
      categoryId: createdCategories[7]?.id || '',
      subcategory: 'Plants',
      images: [
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
      ],
      colors: ['Green'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 12,
      rating: 4.8,
      reviewCount: 8,
      tags: ['fiddle leaf', 'elegant', 'modern'],
      features: ['Large leaves', 'Elegant design', 'Modern style'],
      care: ['Water weekly', 'Bright indirect light', 'High humidity'],
      isActive: true,
      isFeatured: true,
      weight: 3.0,
      length: 30,
      width: 30,
      height: 80,
      dimensionUnit: 'cm',
    },
    // Centerpieces
    {
      name: 'Wedding Centerpiece',
      slug: generateSlug('Wedding Centerpiece'),
      description: 'An elegant centerpiece perfect for weddings and special occasions. Features white and blush flowers.',
      price: 75.99,
      categoryId: createdCategories[8]?.id || '',
      subcategory: 'Centerpieces',
      images: [
        'https://images.unsplash.com/photo-1597848212624-e17eb5d2e0b4?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['White', 'Blush'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 15,
      rating: 4.9,
      reviewCount: 12,
      tags: ['wedding', 'elegant', 'white', 'blush'],
      features: ['Wedding design', 'Elegant style', 'White and blush'],
      care: ['Keep away from direct sunlight', 'Change water daily'],
      isActive: true,
      isFeatured: true,
      weight: 1.5,
      length: 40,
      width: 30,
      height: 50,
      dimensionUnit: 'cm',
    },
    {
      name: 'Holiday Centerpiece',
      slug: generateSlug('Holiday Centerpiece'),
      description: 'A festive centerpiece perfect for holiday celebrations. Features seasonal flowers and greenery.',
      price: 68.99,
      categoryId: createdCategories[8]?.id || '',
      subcategory: 'Centerpieces',
      images: [
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
      ],
      colors: ['Red', 'Green', 'White'],
      sizes: ['Large', 'Extra Large'],
      stockCount: 20,
      rating: 4.7,
      reviewCount: 15,
      tags: ['holiday', 'festive', 'seasonal'],
      features: ['Holiday theme', 'Seasonal colors', 'Festive design'],
      care: ['Keep in cool place', 'Change water daily'],
      isActive: true,
      isFeatured: false,
      weight: 1.3,
      length: 35,
      width: 25,
      height: 45,
      dimensionUnit: 'cm',
    },
    // Decorations
    {
      name: 'Floating Candles with Flowers',
      slug: generateSlug('Floating Candles with Flowers'),
      description: 'Elegant floating candles with flower petals. Perfect for creating a romantic and magical atmosphere.',
      price: 42.99,
      categoryId: createdCategories[9]?.id || '',
      subcategory: 'Decorations',
      images: [
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
      ],
      colors: ['White', 'Pink'],
      sizes: ['Medium', 'Large'],
      stockCount: 30,
      rating: 4.5,
      reviewCount: 18,
      tags: ['romantic', 'candles', 'floating'],
      features: ['Floating candles', 'Flower petals', 'Romantic atmosphere'],
      care: ['Keep away from direct sunlight', 'Replace candles as needed'],
      isActive: true,
      isFeatured: false,
      weight: 0.5,
      length: 25,
      width: 25,
      height: 15,
      dimensionUnit: 'cm',
    },
    {
      name: 'Dried Flower Wall Art',
      slug: generateSlug('Dried Flower Wall Art'),
      description: 'Beautiful dried flower arrangement framed as wall art. Perfect for adding natural beauty to any space.',
      price: 58.99,
      originalPrice: 68.99,
      categoryId: createdCategories[9]?.id || '',
      subcategory: 'Decorations',
      images: [
        'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
      ],
      colors: ['Mixed'],
      sizes: ['Medium', 'Large'],
      stockCount: 25,
      rating: 4.6,
      reviewCount: 13,
      tags: ['dried flowers', 'wall art', 'decorative'],
      features: ['Dried flowers', 'Framed art', 'Long lasting'],
      care: ['Keep away from direct sunlight', 'Dust gently'],
      isActive: true,
      isFeatured: true,
      weight: 0.8,
      length: 30,
      width: 20,
      height: 2,
      dimensionUnit: 'cm',
    },
  ];

  for (const productData of products) {
    const product = await prisma.product.upsert({
      where: { slug: productData.slug },
      update: {},
      create: productData,
    });
    logger.info('✅ Product created:', product.name);
  }

  // Create sample addresses for the test user
  const addresses = [
    {
      userId: user.id,
      type: 'SHIPPING' as const,
      firstName: 'John',
      lastName: 'Doe',
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'United States',
      phone: '+1-555-0123',
      isDefault: true,
    },
    {
      userId: user.id,
      type: 'BILLING' as const,
      firstName: 'John',
      lastName: 'Doe',
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'United States',
      phone: '+1-555-0123',
      isDefault: true,
    },
  ];

  for (const addressData of addresses) {
    const address = await prisma.address.create({
      data: addressData,
    });
    logger.info('✅ Address created for user:', address.type);
  }

  // Create sample coupons
  const coupons = [
    {
      code: 'WELCOME10',
      description: 'Welcome discount for new customers',
      type: 'percentage',
      value: 10,
      minimumAmount: 25,
      isActive: true,
      validFrom: new Date(),
      validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // 1 year
      usageLimit: 1000,
    },
    {
      code: 'SAVE20',
      description: 'Save $20 on orders over $100',
      type: 'fixed',
      value: 20,
      minimumAmount: 100,
      isActive: true,
      validFrom: new Date(),
      validUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 3 months
      usageLimit: 500,
    },
  ];

  for (const couponData of coupons) {
    const coupon = await prisma.coupon.create({
      data: couponData,
    });
    logger.info('✅ Coupon created:', coupon.code);
  }

  logger.info('🎉 Database seeding completed successfully!');
  logger.info('\n📋 Test Accounts:');
  logger.info('Admin: admin@flowerhub.com / admin123');
  logger.info('User: user@flowerhub.com / user123');
  logger.info('\n🎁 Sample Coupons:');
  logger.info('WELCOME10 - 10% off orders over $25');
  logger.info('SAVE20 - $20 off orders over $100');
}

main()
  .catch((e) => {
    logger.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
